- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt update

  - name : Install Docker
    command : sudo apt install docker.io -y
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl restart docker
    become : yes
    become_user : root

  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 rahul9711/insure-me:3.0
